version: '3.7'

services:
  mongo_db1:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27017:27017
    volumes:
      - mongoData1:/data/db
      - mongoConfig1:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 1
          - node.role == manager

  mongo_express:
    image: mongo-express:0.54.0
    networks:
      - mongo-net
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo_db1
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    volumes:
       - mongoData2:/data/db
       - mongoConfig2:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 1
          - node.role == manager
    depends_on:
      - mongo_db1

  mongo_db2:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27018:27017
    volumes:
      - mongoData3:/data/db
      - mongoConfig3:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 2
          - node.role == worker

  mongo_db3:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27019:27017
    volumes:
      - mongoData4:/data/db
      - mongoConfig4:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 3
          - node.role == worker

  mongo_db4:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27020:27017
    volumes:
      - mongoData5:/data/db
      - mongoConfig5:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 4
          - node.role == worker

  mongo_db5:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27021:27017
    volumes:
      - mongoData6:/data/db
      - mongoConfig6:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 5
          - node.role == worker

  mongo_db6:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27022:27017
    volumes:
      - mongoData7:/data/db
      - mongoConfig7:/data/configdb
    deploy:
      mode: replicated
      update_config:
        parallelism: 2
        delay: 10s
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 6
          - node.role == worker

  mongo_db7:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27023:27017
    volumes:
      - mongoData8:/data/db
      - mongoConfig8:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 7
          - node.role == worker

  mongo_db8:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27024:27017
    volumes:
      - mongoData9:/data/db
      - mongoConfig9:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 8
          - node.role == worker

  mongo_db9:
    image: mongo:4.2.12
    command: ["mongod", "--replSet", "test-rs"]
    networks:
      - mongo-net
    ports:
      - 27025:27017
    volumes:
      - mongoData10:/data/db
      - mongoConfig10:/data/configdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.labels.mongo.replica == 9
          - node.role == worker

  #mongo_db10:
   # image: mongo:4.2.12
    #command: ["mongod", "--replSet", "test-rs"]
   # networks:
    #  - mongo-net
    #ports:
     # - 27026:27017
    #volumes:
     # - mongoData11:/data/db
      #- mongoConfig11:/data/configdb
    #deploy:
     # mode: replicated
      #replicas: 1
      #update_config:
       # parallelism: 2
        #delay: 10s
      #placement:
       # constraints:
         # - node.labels.mongo.replica == 10
        #  - node.role == worker

networks:
  mongo-net:
    external: true

volumes:
  mongoData1:
  mongoConfig1:
  mongoData2:
  mongoConfig2:
  mongoData3:
  mongoConfig3:
  mongoData4:
  mongoConfig4:
  mongoData5:
  mongoConfig5:
  mongoData6:
  mongoConfig6:
  mongoData7:
  mongoConfig7:
  mongoData8:
  mongoConfig8:
  mongoData9:
  mongoConfig9:
  mongoData10:
  mongoConfig10:
#  mongoData11:
 # mongoConfig11:
